### ISSUE TITLE
Lab report 4 feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [suprithk/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
- [ ] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program

Snippet 2

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
- [ ] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program

Snippet 3

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
- [ ] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program

Additional comments from your grader:
- Unfinished except for provided links

Feel free to comment below any questions about the rubric/feedback

**Comment by suprithk** [comment]
Hey, I have checked the requirements and have done as thorough a job as possible from my side. Let me know if there is something else.

**Comment by suprithk** [comment]
> Here is your feedback for Lab Report 4:
> 
> * [x]  Provides link to their markdown-parse repository
> * [x]  Provides link to the markdown-parse repository they reviewed
> 
> Snippet 1
> 
> * [x]  Shows the test(s) / expected output in MarkdownParseTest.java
> * [x]  Shows the output of running test(s) for their implementation
> * [x]  Shows the output of running for the implementation they reviewed
> * [x]  Answers the code change question about their program
> 
> Snippet 2
> 
> * [x]  Shows the test(s) / expected output in MarkdownParseTest.java
> * [x]  Shows the output of running test(s) for their implementation
> * [x]  Shows the output of running for the implementation they reviewed
> * [x]  Answers the code change question about their program
> 
> Snippet 3
> 
> * [x]  Shows the test(s) / expected output in MarkdownParseTest.java
> * [x]  Shows the output of running test(s) for their implementation
> * [x]  Shows the output of running for the implementation they reviewed
> * [x]  Answers the code change question about their program
> 
> Additional comments from your grader:
> 
> * Unfinished except for provided links
> 
> Feel free to comment below any questions about the rubric/feedback

Hey, I have checked the requirements and have done as thorough a job as possible from my side. Let me know if there is something else.
